name: Test RST Autoformatter

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run RST Autoformatter
        uses: livxy/rst-autoformatter-action@main
        with:
          commit: 'true'
          github-username: 'github-actions'
          commit-message: 'Automated RST formatting'
          files: '**/*.rst'
