name: Test RST Autoformatter

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Run RST Autoformatter
        uses: livxy/rst-autoformatter-action@main
        with:
          # files: '**/*.rst' # works!
          # files: 'tests/lines.rst' # works!
          files: 'tests/admonitions.rst, tests/escaped-text.rst'
          commit: 'true'
          github-username: 'github-actions'
          commit-message: 'Automated RST formatting'

