name: Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Test Formatting
        run: |
          rstfmt tests/test_file1.rst
          echo "test_file1.rst"
          echo "========="
          cat tests/test_file1.rst
          echo ""
          echo "test_file2.rst"
          echo "========="
          cat tests/test_file2.rst
          echo ""
          diff -q tests/test_file1.rst tests/test_file2.rst > /dev/null
          if [ $? -eq 0 ]; then
            echo "PASS: Files are the same"
          else
            echo "FAIL: Files differ"
            exit 1
          fi
